// Database types - will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --local > types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string | null
          full_name: string | null
          avatar_url: string | null
          stripe_customer_id: string | null
          subscription_status: string
          subscription_tier: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email?: string | null
          full_name?: string | null
          avatar_url?: string | null
          stripe_customer_id?: string | null
          subscription_status?: string
          subscription_tier?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string | null
          full_name?: string | null
          avatar_url?: string | null
          stripe_customer_id?: string | null
          subscription_status?: string
          subscription_tier?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      landing_pages: {
        Row: {
          id: string
          user_id: string
          name: string
          slug: string | null
          content: Json
          theme: Json | null
          metadata: Json | null
          is_published: boolean
          posthog_dashboard_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          slug?: string | null
          content: Json
          theme?: Json | null
          metadata?: Json | null
          is_published?: boolean
          posthog_dashboard_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          slug?: string | null
          content?: Json
          theme?: Json | null
          metadata?: Json | null
          is_published?: boolean
          posthog_dashboard_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      agent_sessions: {
        Row: {
          id: string
          user_id: string
          agent_type: string
          landing_page_id: string | null
          messages: Json
          context: Json | null
          title: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          agent_type: string
          landing_page_id?: string | null
          messages?: Json
          context?: Json | null
          title?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          agent_type?: string
          landing_page_id?: string | null
          messages?: Json
          context?: Json | null
          title?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      research_reports: {
        Row: {
          id: string
          user_id: string
          landing_page_id: string | null
          idea_description: string
          competitors: Json | null
          market_size: Json | null
          target_audience: Json | null
          opportunities: Json | null
          risks: Json | null
          sources: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          landing_page_id?: string | null
          idea_description: string
          competitors?: Json | null
          market_size?: Json | null
          target_audience?: Json | null
          opportunities?: Json | null
          risks?: Json | null
          sources?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          landing_page_id?: string | null
          idea_description?: string
          competitors?: Json | null
          market_size?: Json | null
          target_audience?: Json | null
          opportunities?: Json | null
          risks?: Json | null
          sources?: Json | null
          created_at?: string
        }
      }
      social_insights: {
        Row: {
          id: string
          user_id: string
          landing_page_id: string | null
          query: string
          platform: string | null
          sentiment_summary: Json | null
          pain_points: Json | null
          feature_requests: Json | null
          raw_mentions: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          landing_page_id?: string | null
          query: string
          platform?: string | null
          sentiment_summary?: Json | null
          pain_points?: Json | null
          feature_requests?: Json | null
          raw_mentions?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          landing_page_id?: string | null
          query?: string
          platform?: string | null
          sentiment_summary?: Json | null
          pain_points?: Json | null
          feature_requests?: Json | null
          raw_mentions?: Json | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']

// Convenience aliases
export type Profile = Tables<'profiles'>
export type LandingPage = Tables<'landing_pages'>
export type AgentSession = Tables<'agent_sessions'>
export type ResearchReport = Tables<'research_reports'>
export type SocialInsight = Tables<'social_insights'>
